const config = window.projectConfig;
const stage = document.querySelector("#stage");
const searchInput = document.querySelector("#searchInput");
const addButton = document.querySelector("#addEntry");
const inputA = document.querySelector("#entryA");
const inputB = document.querySelector("#entryB");
const inputC = document.querySelector("#entryC");
const shuffleButton = document.querySelector("#shuffleButton");
let items = config.items.map((item, index) => ({ ...item, id: crypto.randomUUID ? crypto.randomUUID() : String(index + Date.now()) }));
let filterText = "";
document.documentElement.style.setProperty("--accent", config.accent);
function getItems() { return items.filter((item) => [item.a, item.b, item.c].join(" ").toLowerCase().includes(filterText)); }
function renderHeatmap(list) { const days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]; stage.innerHTML = list.map((item, index) => { const count = Number(item.c) || 0; const cells = days.map((day, dayIndex) => `<button class="cell ${dayIndex < count ? "active" : ""}" data-index="${index}" data-day="${dayIndex}" type="button" aria-label="${day}"></button>`).join(""); return `<article class="row"><div><strong>${item.a}</strong><div class="muted">${item.b}</div></div>${cells}</article>`; }).join(""); }
function renderCountdowns(list) { stage.innerHTML = list.map((item) => `<article class="card"><p class="pill">${item.a}</p><p class="metric">${item.b}</p><p class="muted">${item.c} left</p></article>`).join(""); }
function renderRecipes(list) { stage.innerHTML = list.map((item) => `<article class="card"><p class="pill">${item.b}</p><h3>${item.a}</h3><p class="muted">Prep: ${item.c}</p></article>`).join(""); }
function renderExpenses(list) { stage.innerHTML = list.map((item) => `<div class="row"><strong>${item.a}</strong><span class="pill">${item.b}</span><span>Rs ${item.c}</span><button data-id="${item.id}" class="remove">Remove</button></div>`).join(""); }
function renderStudy(list) { stage.innerHTML = list.map((item, index) => `<article class="card" style="--fill:${Math.min(95, 25 + index * 20)}%"><div class="inner"><div><p class="pill">${item.b}</p><h3>${item.a}</h3><p class="muted">${item.c}</p></div></div></article>`).join(""); }
function renderPalette(list) { stage.innerHTML = list.map((item) => `<article class="swatch"><div class="tone" style="background:${item.b}"></div><div class="swatch-info"><strong>${item.a}</strong><p class="muted">${item.b} · ${item.c}</p></div></article>`).join(""); }
function renderKanban(list) { const groups = { Now: [], Next: [], Later: [] }; list.forEach((item) => (groups[item.b] || groups.Later).push(item)); stage.innerHTML = Object.entries(groups).map(([key, values]) => `<section class="lane"><h3>${key}</h3>${values.map((item) => `<article class="ticket"><strong>${item.a}</strong><p class="muted">${item.c}</p></article>`).join("")}</section>`).join(""); }
function renderWeather(list) { stage.innerHTML = list.map((item) => `<article class="day-card"><p class="pill">${item.a}</p><p class="temp">${item.b}°</p><p class="muted">${item.c}</p></article>`).join(""); }
function renderPortfolio(list) { stage.innerHTML = list.map((item) => `<article class="strip"><div class="year">${item.c}</div><div><p class="pill">${item.b}</p><h3>${item.a}</h3></div><button data-id="${item.id}" class="remove">Archive</button></article>`).join(""); }
function renderBookmarks(list) { stage.innerHTML = list.map((item, index) => `<article class="bookmark" style="min-height:${140 + (index % 3) * 40}px"><p class="pill">${item.c}</p><h3>${item.a}</h3><p class="muted">${item.b}</p></article>`).join(""); }
function renderNotes(list) { const colors = { amber: "#fde68a", rose: "#fda4af", sky: "#7dd3fc", lime: "#bef264", violet: "#c4b5fd" }; stage.innerHTML = list.map((item, index) => `<article class="note" style="background:${colors[item.c] || "#fde68a"};--tilt:${index % 2 === 0 ? "-2deg" : "2deg"}"><p class="pill">${item.b}</p><h3>${item.a}</h3></article>`).join(""); }
function renderMovies(list) { const [featured, ...rest] = list; stage.innerHTML = `<article class="featured"><p class="pill">${featured.b}</p><h2>${featured.a}</h2><p class="rating">${featured.c}</p><p class="muted">Featured pick tonight.</p></article><div class="sidebar">${rest.map((item) => `<article class="sidebar-card"><p class="pill">${item.b}</p><strong>${item.a}</strong><p class="muted">Rating ${item.c}</p></article>`).join("")}</div>`; }
function renderPacking(list) { stage.innerHTML = list.map((item) => `<article class="pack-row"><strong>${item.a}</strong><span class="pill">${item.b}</span><span>${item.c} pcs</span><input type="checkbox"></article>`).join(""); }
function renderFitness(list) { stage.innerHTML = list.map((item) => `<article class="session"><p class="pill">${item.b}</p><h3>${item.a}</h3><p class="muted">${item.c}</p></article>`).join(""); }
function renderInvoice(list) { const total = list.reduce((sum, item) => sum + Number(item.b) * Number(item.c), 0); stage.innerHTML = `<table><thead><tr><th>Service</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${list.map((item) => `<tr><td>${item.a}</td><td>${item.b}</td><td>${item.c}</td><td>${Number(item.b) * Number(item.c)}</td></tr>`).join("")}</tbody></table><div class="total">Total: Rs ${total}</div>`; }
function renderReading(list) { stage.innerHTML = list.map((item, index) => `<article class="book" style="--height:${180 + index * 28}px"><div><strong>${item.a}</strong><p class="muted">${item.b}% · ${item.c}</p></div></article>`).join(""); }
function renderPassword(list) { const strength = Math.min(96, 20 + list.length * 18); stage.innerHTML = `<section class="meter"><h3>Strength Estimate</h3><div class="bar"><div class="knob" style="left:${strength}%"></div></div><p class="muted">${strength >= 70 ? "Strong" : "Needs work"} password posture.</p></section><section class="tips">${list.map((item) => `<article><p class="pill">${item.c}</p><strong>${item.a}</strong><p class="muted">${item.b}</p></article>`).join("")}</section>`; }
function renderTyping(list) { stage.innerHTML = `<p><span class="prompt">guest@speed-test:~$</span> begin round</p>${list.map((item, index) => `<div class="quote"><p>${item.a}</p><p class="muted">Prompt ${index + 1}</p></div>`).join("")}`; }
function renderThemes(list) { const palettes = ["linear-gradient(135deg,#f4a261,#e76f51)","linear-gradient(135deg,#111827,#374151)","linear-gradient(135deg,#34d399,#059669)"]; stage.innerHTML = list.map((item, index) => `<article class="theme-card" style="background:${palettes[index % palettes.length]}"><div><p class="pill">${item.b}</p><h3>${item.a}</h3></div><p>${item.c}</p></article>`).join(""); }
function renderProducts(list) { stage.innerHTML = list.map((item) => `<article class="product"><p class="pill">${item.b}</p><h3>${item.a}</h3><p class="price">$${item.c}</p></article>`).join(""); }
function renderQuiz(list) { stage.innerHTML = list.map((item) => `<article class="quiz-card" data-id="${item.id}"><div class="quiz-inner"><div class="face front"><p class="pill">${item.c}</p><h3>${item.a}</h3><p class="muted">Tap to reveal</p></div><div class="face back"><p class="pill">Answer</p><h3>${item.b}</h3></div></div></article>`).join(""); }
function renderFeedback(list) { stage.innerHTML = list.map((item) => `<article class="bar-row"><strong>${item.a}</strong><div class="track"><div class="fill" style="--width:${item.c}%"></div></div><span>${item.c}%</span></article>`).join(""); }
function renderMusic(list) { stage.innerHTML = list.map((item, index) => `<article class="track"><div><p class="pill">${item.b}</p><h3>${item.a}</h3></div><div class="bars"><span style="--h:${16 + index * 6}px"></span><span style="--h:${30 + index * 3}px"></span><span style="--h:${22 + index * 8}px"></span><span style="--h:${36 - index * 2}px"></span><span style="--h:${20 + index * 5}px"></span></div><span>${item.c} tracks</span></article>`).join(""); }
function renderCurrency(list) { stage.innerHTML = `<section class="screen"><p class="pill">Converter</p><div class="amount">1250</div><p class="muted">Base amount preview</p><div class="keypad">${["7","8","9","4","5","6","1","2","3"].map((key) => `<div class="key">${key}</div>`).join("")}</div></section><section class="rates">${list.map((item) => `<div class="row"><strong>${item.a}/${item.b}</strong><span class="pill">Rate</span><span>${item.c}</span></div>`).join("")}</section>`; }
function renderPlanner(list) { stage.innerHTML = list.map((item) => `<article class="plan-row"><strong>${item.b}</strong><span>${item.a}</span><span class="pill">${item.c}</span><input type="checkbox" ${item.c === "Done" ? "checked" : ""}></article>`).join(""); }
const renderers = { heatmap: renderHeatmap, sunset: renderCountdowns, paper: renderRecipes, ledger: renderExpenses, focus: renderStudy, gallery: renderPalette, kanban: renderKanban, forecast: renderWeather, editorial: renderPortfolio, masonry: renderBookmarks, sticky: renderNotes, cinema: renderMovies, packing: renderPacking, fitness: renderFitness, invoice: renderInvoice, bookshelf: renderReading, security: renderPassword, terminal: renderTyping, "theme-lab": renderThemes, shop: renderProducts, flash: renderQuiz, analytics: renderFeedback, audio: renderMusic, calc: renderCurrency, planner: renderPlanner };
function render() { renderers[config.mode](getItems()); }
searchInput.addEventListener("input", (event) => { filterText = event.target.value.toLowerCase(); render(); });
addButton.addEventListener("click", () => { const a = inputA.value.trim(); const b = inputB.value.trim(); const c = inputC.value.trim(); if (!a || !b || !c) return; items.unshift({ a, b, c, id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()) }); inputA.value = ""; inputB.value = ""; inputC.value = ""; render(); });
shuffleButton.addEventListener("click", () => { items = [...items].sort(() => Math.random() - 0.5); render(); });
stage.addEventListener("click", (event) => { const removeButton = event.target.closest(".remove"); const quizCard = event.target.closest(".quiz-card"); const heatCell = event.target.closest(".cell"); if (removeButton) { items = items.filter((item) => item.id !== removeButton.dataset.id); render(); } if (quizCard) { quizCard.classList.toggle("flipped"); } if (heatCell) { const rowIndex = Number(heatCell.dataset.index); const dayIndex = Number(heatCell.dataset.day); const current = Number(items[rowIndex].c) || 0; items[rowIndex].c = dayIndex < current ? String(dayIndex) : String(dayIndex + 1); render(); } });
render();
